#include <windows.h>
#include <stdio.h>
#include <iostream>
#include <time.h>
#include <string.h>
#include <vector>
#include "../freeglut/glut.h"
#include "QUAD.h"
#include "Plane.h"
#include "Bullet.h"
#include "BulletManager.h"
#include "EnemyManager.h"
#include "Data.h"
#include "ConstData.h"
#include "GameTimer.h"
#include "LoadTextureFunc.h"
#include "StageScript.h"